#!/bin/bash
#PBS -l walltime=0:45:00
#PBS -l mem=500m
#PBS -N archives1safe
#PBS -j oe
#PBS -m n
#PBS -q gpd
# I need queue GPU because node of old datarmor grappe dont have /scale access March 25
echo 'script to archive Sentinel-1 in Ifremer database'
# input will contain --input-safe SAFE --archivename scale (for example)
echo "SAFE source: "$1 $2 $3 $4

. /appli/anaconda/2.7/etc/profile.d/conda.sh
source /etc/profile.d/modules.sh #recommende par RIC mars 2020
pythonbin=/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/l1bAdev
conda activate $pythonbin
which python
echo 'pybin:'$pybin

#archivesafe --input-safe $1
archivesafe $1 $2 $3 $4

